app:
  host: 0.0.0.0
  mode: debug
  port: 8080
  idle_timeout: 15s
  max_multipart_memory: 10485760
  read_timeout: 5s
  write_timeout: 10s

jwt:
  audience: api-users
  expire_hours: 2
  issuer: dnsm
  refresh_hours: 24
  secret_key: default-secret-key-32bytes-long-1234
  signing_method: HS256

login:
  username: admin
  password: admin123
