opskvm_app:
  opskvm_name: "opskvm"
  opskvm_host: "0.0.0.0"
  opskvm_mode: "debug"
  opskvm_port: 8080
  opskvm_video_path: "" # 空字符串表示自动检测
  opskvm_video_width: 1920
  opskvm_video_height: 1080
  opskvm_video_fps: 30
  opskvm_kmhid_mode: "otg" # "otg" or "ch9329"
  opskvm_idle_timeout: "15s"
  opskvm_max_multipart_memory: "10485760"
  opskvm_read_timeout: "5s"
  opskvm_write_timeout: "10s"

opskvm_jwt:
  opskvm_audience: "api-users"
  opskvm_expire_hours: 2
  opskvm_issuer: "opskvm"
  opskvm_refresh_hours: 24
  opskvm_secret_key: "default-secret-key-32bytes-long-1234"
  opskvm_signing_method: "HS256"

opskvm_login:
  username: "admin"
  password: "admin123"
