// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package mirrors

import (
	mirrors "opskvm/api/mirrors"
	mirrorslogic "opskvm/internal/logic/mirrors"
)

type ControllerV1 struct {
	mirrors *mirrorslogic.Mirrors
}

func NewV1() mirrors.IMirrorsV1 {
	return &ControllerV1{
		mirrors: mirrorslogic.New(),
	}
}