// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package system

import (
	"opskvm/api/system"
	systemlogic "opskvm/internal/logic/system"
)

type ControllerV1 struct {
	sys *systemlogic.System
}

func NewV1() system.ISystemV1 {
	return &ControllerV1{
		sys: systemlogic.New(),
	}
}
