// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package totp

import (
	"opskvm/api/totp"
	totpLogic "opskvm/internal/logic/totp"
)

type ControllerV1 struct {
	totp *totpLogic.Totp
}

func NewV1() totp.ITotpV1 {
	return &ControllerV1{
		totp: totpLogic.TotpInstance,
	}
}
