// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package kvm

import (
	"opskvm/api/kvm"
	kvmlogic "opskvm/internal/logic/kvm"
)

type ControllerV1 struct {
	kvm *kvmlogic.KVM
}

func NewV1() kvm.IKvmV1 {
	return &ControllerV1{
		kvm: kvmlogic.New(),
	}
}
