// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package files

import (
	"opskvm/api/files"
	fileslogic "opskvm/internal/logic/files"
)

type ControllerV1 struct {
	Files *fileslogic.FILES
}

func NewV1() files.IFilesV1 {
	return &ControllerV1{
		Files: fileslogic.New(),
	}
}
