// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"opskvm/internal/dao/internal"
)

// wolDao is the data access object for the table wol.
// You can define custom methods on it to extend its functionality as needed.
type wolDao struct {
	*internal.WolDao
}

var (
	// Wol is a globally accessible object for table wol operations.
	Wol = wolDao{internal.NewWolDao()}
)

// Add your custom methods and functionality below.
