// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package webshell

import (
	"opskvm/api/webshell"
	webshelllogic "opskvm/internal/logic/webshell"
)

type ControllerV1 struct {
	webshell *webshelllogic.WebShell
}

func NewV1() webshell.IWebshellV1 {
	return &ControllerV1{
		webshell: webshelllogic.New(),
	}
}
