// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package wake

import (
	"opskvm/api/wake"
	wakelogic "opskvm/internal/logic/wake"
)

type ControllerV1 struct {
	Wake *wakelogic.Wake
}

func NewV1() wake.IWakeV1 {
	return &ControllerV1{
		Wake: wakelogic.New(),
	}
}
